// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD20uWmeANN1xuPBSAB6YSR1kWAgnbDqy0',
    appId: '1:208166400766:web:074ce509595b097d296baf',
    messagingSenderId: '208166400766',
    projectId: 'gentech-4aa53',
    authDomain: 'gentech-4aa53.firebaseapp.com',
    storageBucket: 'gentech-4aa53.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDy0LudoUR62bIODsj_D0JPPeUOKvR1lQo',
    appId: '1:208166400766:android:5208945df8cfb604296baf',
    messagingSenderId: '208166400766',
    projectId: 'gentech-4aa53',
    storageBucket: 'gentech-4aa53.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAdLxBXhiwVwlfaWbFxN8hKwg298y_VA1c',
    appId: '1:208166400766:ios:ce6e606b69c34bda296baf',
    messagingSenderId: '208166400766',
    projectId: 'gentech-4aa53',
    storageBucket: 'gentech-4aa53.appspot.com',
    iosBundleId: 'com.example.gentech',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAdLxBXhiwVwlfaWbFxN8hKwg298y_VA1c',
    appId: '1:208166400766:ios:ce6e606b69c34bda296baf',
    messagingSenderId: '208166400766',
    projectId: 'gentech-4aa53',
    storageBucket: 'gentech-4aa53.appspot.com',
    iosBundleId: 'com.example.gentech',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD20uWmeANN1xuPBSAB6YSR1kWAgnbDqy0',
    appId: '1:208166400766:web:9d659e4356f492f2296baf',
    messagingSenderId: '208166400766',
    projectId: 'gentech-4aa53',
    authDomain: 'gentech-4aa53.firebaseapp.com',
    storageBucket: 'gentech-4aa53.appspot.com',
  );
}
